/**
 * Discriminants tagging each board's save-state shape. Capture and restore refer
 * to the same named kind instead of repeating bare string literals; the
 * `MapperState` union in mapper.ts remains the canonical type definition.
 */
export const MapperKind = {
  Nrom: "nrom",
  AddressLatchMulticart: "address-latch-multicart",
  Uxrom: "uxrom",
  Cnrom: "cnrom",
  VsSystem: "vs-system",
  Bnrom: "bnrom",
  Nina001: "nina-001",
  Axrom: "axrom",
  Gxrom: "gxrom",
  ColorDreams: "color-dreams",
  Cprom: "cprom",
  Codemasters: "codemasters",
  Bandai74: "bandai-74",
  BandaiFcg: "bandai-fcg",
  FfeMagicCard: "ffe-magic-card",
  Jaleco87: "jaleco-87",
  JalecoJf: "jaleco-jf",
  JalecoSs8806: "jaleco-ss8806",
  JyCompany: "jy-company",
  Jy830623c: "jy-830623c",
  Ej0061: "ej-006-1",
  Namco163: "namco-163",
  Mmc5: "mmc5",
  Namco118: "namco-118",
  Sunsoft1: "sunsoft-1",
  Sunsoft2: "sunsoft-2",
  Sunsoft3R: "sunsoft-3r",
  CnromProtection: "cnrom-protection",
  TaitoTc0190: "taito-tc0190",
  TaitoTc0690: "taito-tc0690",
  TaitoX1005: "taito-x1-005",
  TaitoX1017: "taito-x1-017",
  ConyYoko: "cony-yoko",
  IremG101: "irem-g101",
  IremH3001: "irem-h3001",
  Rambo1: "rambo-1",
  Sunsoft4: "sunsoft-4",
  Nina0306: "nina-03-06",
  HesNtd8: "hes-ntd8",
  NtdecAsder: "ntdec-asder",
  IremTamS1: "irem-tam-s1",
  Irem78: "irem-78",
  Vrc1: "vrc1",
  Vrc3: "vrc3",
  Vrc2Vrc4: "vrc2-vrc4",
  Vrc6: "vrc6",
  Vrc7: "vrc7",
  Mmc1: "mmc1",
  Mmc2: "mmc2",
  Mmc3: "mmc3",
  Mmc4: "mmc4",
  Fme7: "fme7",
} as const;

export type MapperKind = (typeof MapperKind)[keyof typeof MapperKind];
